depends_on:
  - test

clone:
  git:
    disable: true

when:
  - event: push
    branch: main
  - event: tag

steps:
  - name: clone
    image: alpine/git
    commands:
      - apk add --no-cache curl
      - git clone https://admin:9382bd0ae1d5fc1af2aee1d330f92c6b2aac0258@gitea.csceccloud.net:1443/admin/ocr-demo.git .
      - git checkout $CI_COMMIT_BRANCH 2>/dev/null || git checkout $CI_COMMIT_TAG 2>/dev/null || true

  - name: build-and-push
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASSWORD:
        from_secret: registry_password
      REGISTRY_URL: registry.cn-beijing.aliyuncs.com
      NAMESPACE: woodpeacker
      DOCKER_BUILDKIT: 1
    commands:
      - echo "$REGISTRY_PASSWORD" | docker login $REGISTRY_URL -u "$REGISTRY_USER" --password-stdin
      - docker build --cache-from $REGISTRY_URL/$NAMESPACE/ocr-demo:latest -t $REGISTRY_URL/$NAMESPACE/ocr-demo:latest .
      - if [ -n "$CI_COMMIT_TAG" ]; then
          docker tag $REGISTRY_URL/$NAMESPACE/ocr-demo:latest $REGISTRY_URL/$NAMESPACE/ocr-demo:$CI_COMMIT_TAG;
        fi
      - docker push $REGISTRY_URL/$NAMESPACE/ocr-demo --all-tags
